package com.infectapp.presentation

const val SPLASH_DELAY = 3000L

const val ANIMATION_DURATION = 500L
const val ANIMATION_DURATION_FAST = 250L
const val ANIMATION_DURATION_VERY_FAST = 100L

const val KODEIN_TAG_DIALOG_FINGERPRINT = "KODEIN_TAG_DIALOG_FINGERPRINT"
const val KODEIN_TAG_DIALOG_SLIDER = "KODEIN_TAG_DIALOG_SLIDER"
const val KODEIN_TAG_DIALOG_SIMPLE = "KODEIN_TAG_DIALOG_SIMPLE"
const val KODEIN_TAG_DIALOG_INFO = "KODEIN_TAG_DIALOG_INFO"
const val KODEIN_TAG_DIALOG_PHONE = "KODEIN_TAG_DIALOG_PHONE"
const val KODEIN_TAG_DIALOG_ATTENTION = "KODEIN_TAG_DIALOG_ATTENTION"
const val KODEIN_TAG_DIALOG_LOADING = "KODEIN_TAG_DIALOG_LOADING"
const val KODEIN_TAG_DIALOG_SELECTOR = "KODEIN_TAG_DIALOG_SELECTOR"
const val KODEIN_TAG_DIALOG_REPORT = "KODEIN_TAG_DIALOG_REPORT"
const val KODEIN_TAG_DIALOG_LOCATION = "KODEIN_TAG_DIALOG_LOCATION"
const val KODEIN_TAG_DIALOG_ACCEPT = "KODEIN_TAG_DIALOG_ACCEPT"
const val KODEIN_TAG_DIALOG_CONTEXT_APP = "KODEIN_TAG_DIALOG_CONTEXT_APP"
const val KODEIN_TAG_DIALOG_CONTEXT_ACTIVITY = "KODEIN_TAG_DIALOG_CONTEXT_ACTIVITY"

const val PROPORTION_DIALOG_WIDTH_DEFAULT = 3.5f / 5

const val CAPITAL_EMPTY = "0,00 €"

const val SIMBOL_EURO = "€"

const val DEFAULT_CLICK_LISTENER_THRESHOLD = 500L

const val COLLECTION_USERS = "users"
const val COLLECTION_INVITE_NUMBERS = "invite_numbers"

const val FIELD_MONEY = "money"
const val FIELD_INVITEDNUMBER = "invitedNumber"
const val FIELD_REGISTED = "registed"
const val FIELD_PERSONAL_INVITE_NUMBER = "personalInviteNumber"
